version: '3.9'

services:
  api:
    image: api_image
    container_name: api_container
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      - DB_HOST=db_mimi
      - DB_PORT=PORT
    networks:
      - appi_net

networks:
  appi_net:
