version: '3.9'
services:
  dodo:
    image: dodoImage
    container_name: dodoCon
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    links:
      - bd
    depends_on:
      - bd
    volumes:
      - .:/home/app/
      - /app/node_modules
    restart: unless-stopped
    environment:
      - DB_PORT=PORT
    networks:
      - dodoNet

  bd:
    container_name: myDB
    image: mysql:8.0.32
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=ju123
      - MYSQL_DATABASE=default
    volumes:
      - volumenDB:/var/lib/mysql

volumes:
  volumenDB:

networks:
  dodoNet:
